### ISSUE TITLE
Thoughts on Bastions?

### ISSUE THREAD

**Issue by bmbermn** [jessebye/awser#2]
You seem to already assume you are on the same internal network as your instances, in my case that is not the case. It was easy enough to update the code to pull the IP I needed but I was wondering if you had thoughts on how it may be possible to push through a bastion server. IE ssh into the bastion, then ssh into the private subnet? I cant see a way to do this with subprocess off hand but you may have an idea?

**Comment by JohnPeacockMessageSystems** [comment]
There are a couple of ways to connect via a bastion server, the easiest being 
`ssh -A bastion ssh destination`
which works just fine if you have ssh-agent running. However, an even easier way to do it that requires no code changes at all is to configure your local ssh to connect via ProxyCommand. This page describes both methods pretty well: https://tenmilesquare.com/using-ssh-through-a-bastion-host-transparently/
